"""empty message

Revision ID: 03f83fe672f8
Revises: 
Create Date: 2017-12-04 10:33:51.720219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f83fe672f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tbegin', sa.String(), nullable=True),
    sa.Column('tend', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervals')
    # ### end Alembic commands ###
